version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "huylambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-65rn2cwl7kef"
s3_prefix = "huylambda"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
