version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "huyta"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-a13357b2"
s3_prefix = "huyta"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
