AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  huylambda

  Sample SAM Template for huylambda

Globals:
  Function:
    Timeout: 120

Resources:
  GenenrateS3SignedUrlLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/built/generate_signed_s3_url
      Handler: handler.handler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Policies:
        - Statement:
            - Sid: GenenrateS3SignedUrlLambdaS3Policy
              Effect: Allow
              Action:
                - s3:*
              Resource: 'arn:aws:s3:::huytatest/*'

  SimpleLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/built/simple
      Handler: handler.handler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Policies:
        - Statement:
            - Sid: SimpleLambdaS3Policy
              Effect: Allow
              Action:
                - s3:*
              Resource: 'arn:aws:s3:::huytatest/*'

  ResizeImageLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/built/resize-images
      Handler: handler.imageResizeHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Policies:
        - Statement:
            - Sid: ResizeImageLambdaS3Policy
              Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource: 'arn:aws:s3:::huytatest/*'

  ImageHandlerLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/built/image-handler
      Handler: handler.imageHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Policies:
        - Statement:
            - Sid: ImageHandlerLambdaS3Policy
              Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource: 'arn:aws:s3:::huytatest/*'
